#ifndef _CAN_MAP_H
#define _CAN_MAP_H

#include "stdint.h"

#define PTR(x) (*((uint32_t *)(x)))

#define CAN0_BASE_ADDR 0x40040000
#define CAN1_BASE_ADDR 0x40041000

#define CANCTL_OFFSET     0x000
#define CANSTS_OFFSET     0x004
#define CANERR_OFFSET     0x008
#define CANBIT_OFFSET     0x00C
#define CANINT_OFFSET     0x010
#define CANTST_OFFSET     0x014
#define CANIF1CMSK_OFFSET 0x024
#define CANIF1MSK1_OFFSET 0x028

#define CAN0CTL     (CAN0_BASE_ADDR +     CANCTL_OFFSET)
#define CAN0STS     (CAN0_BASE_ADDR +     CANSTS_OFFSET)
#define CAN0ERR     (CAN0_BASE_ADDR +     CANERR_OFFSET)
#define CAN0BIT     (CAN0_BASE_ADDR +     CANBIT_OFFSET)
#define CAN0INT     (CAN0_BASE_ADDR +     CANINT_OFFSET)
#define CAN0TST     (CAN0_BASE_ADDR +     CANTST_OFFSET)
#define CAN0IF1CMSK (CAN0_BASE_ADDR + CANIF1CMSK_OFFSET)
#define CAN0IF1MSK1 (CAN0_BASE_ADDR + CANIF1MSK1_OFFSET)

#define CAN1CTL     (CAN1_BASE_ADDR +     CANCTL_OFFSET)
#define CAN1STS     (CAN1_BASE_ADDR +     CANSTS_OFFSET)
#define CAN1ERR     (CAN1_BASE_ADDR +     CANERR_OFFSET)
#define CAN1BIT     (CAN1_BASE_ADDR +     CANBIT_OFFSET)
#define CAN1INT     (CAN1_BASE_ADDR +     CANINT_OFFSET)
#define CAN1TST     (CAN1_BASE_ADDR +     CANTST_OFFSET)
#define CAN1IF1CMSK (CAN1_BASE_ADDR + CANIF1CMSK_OFFSET)
#define CAN1IF1MSK1 (CAN1_BASE_ADDR + CANIF1MSK1_OFFSET)

/*                    SYSCTRL Map                       */

#define SYS_CTRL_ADDR_BASE 0x400FE000
#define RCGC0 PTR(SYS_CTRL_ADDR_BASE + 0x100)
#define RCGC2 PTR(SYS_CTRL_ADDR_BASE + 0x108)

/*                    GPIO Map                       */

/* 
 * CAN0 pins are routed to Port B pins 4 and 5
 * CAN1 pins are routed to Port A Pins 0 and 1
 */

#define PORTA_ADDR_BASE 0x40004000
#define PORTB_ADDR_BASE 0x40005000

#define GPIOAFSEL_OFFSET 0x420
#define GPIOPCTL_OFFSET 0x52C

#define GPIOAAFSEL (PORTA_ADDR_BASE + GPIOAFSEL_OFFSET)
#define GPIOBAFSEL (PORTB_ADDR_BASE + GPIOAFSEL_OFFSET)

#define GPIOAPCTL (PORTA_ADDR_BASE + GPIOPCTL_OFFSET)
#define GPIOBPCTL (PORTB_ADDR_BASE + GPIOPCTL_OFFSET)

#endif
